apiVersion: v1
kind: Namespace
metadata:
  name: workspaces
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-bot
  namespace: workspaces
---
apiVersion: v1
kind: Secret
metadata:
  name: workspace-bot-secret
  namespace: workspaces
  annotations:
    kubernetes.io/service-account.name: workspace-bot
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workspace-bot-role
  namespace: workspaces
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workspace-bot-rolebinding
  namespace: workspaces
subjects:
  - kind: ServiceAccount
    name: workspace-bot
    namespace: workspaces
roleRef:
  kind: Role
  name: workspace-bot-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: workspace-bot
  labels:
    app: workspace-bot
spec:
  serviceAccountName: workspace-bot
  containers:
    - name: workspace-bot
      imagePullPolicy: Always
      image: ghcr.io/cscosu/workspace-bot:latest
      env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-token
              key: DISCORD_BOT_TOKEN
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: workspace-network-policy
spec:
  podSelector:
    matchLabels:
      workspace: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.88.0/24
              - 192.168.0.0/16
              - 172.16.0.0/12
              - 10.0.0.0/8
